# -*- coding: utf-8 -*-
"""Visão

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOSNiuG3B2u4nGI1jEvJyLotBnYUIk-6
"""

import cv2

imagem = cv2.imread('/content/Pessoas-felizes.jpg')

#cv2.imshow(imagem)
from google.colab.patches import cv2_imshow
cv2_imshow(imagem)

detector = cv2.CascadeClassifier('/content/haarcascade_frontalface_default.xml')

Img_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
cv2_imshow(Img_cinza)

deteccoes = detector.detectMultiScale(Img_cinza, scaleFactor= 1.1)
deteccoes

for (x, y, l ,a) in deteccoes:
  cv2.rectangle(imagem, (x, y), (x + l, y + a), (0,255,0), 2)
  cv2_imshow(imagem)