# -*- coding: utf-8 -*-
"""Visao_Reconhecimento_de_corpo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPyvAQg1UrGRqYoTrigV3o6Ujqi-89FJ
"""

import cv2

Imagem = cv2.imread('/content/pessoas.jpg')

from google.colab.patches import cv2_imshow
cv2_imshow(Imagem)

detector = cv2.CascadeClassifier('/content/fullbody.xml')

Img_cinza = cv2.cvtColor(Imagem, cv2.COLOR_BGR2GRAY)
cv2_imshow(Img_cinza)

deteccoes = detector.detectMultiScale(Img_cinza)

for (x, y, l, a) in deteccoes:
  cv2.rectangle(Imagem, (x,y), (x + l, y + a), (0, 255, 0) ,2)

cv2_imshow(Imagem)